### ISSUE TITLE
Proje Bitiş Tarihi

### ISSUE THREAD

**Issue by akifgoktas** [ruveydayilmaz/realtime-chat-app#1]
Bu proje bitti mi yoksa devam edip eklenecek özellikler var mı? Şu an alıp kullanılabilir durumda mı?

**Comment by ruveydayilmaz** [comment]
Merhaba, devam ediyor. Bu projeyi kendimi geliştirmek amacıyla yaptığım için kesin bir bitiş tarihi koymadım

**Özellikler**
- [x] gerçek zamanlı mesajlaşma
- [x] online - offline durumu
- [x] yazıyor durumu
- [ ] fotoğraf gönderme (devam ediyor)
- [ ] chat oluşturma
- [ ] mesaj silme
