### ISSUE TITLE
Issue: Chat window doesn't scroll to the bottom

### ISSUE THREAD

**Issue by ruveydayilmaz** [ruveydayilmaz/realtime-chat-app#2]
**Description:** When using the chat feature in the app, the chat window does not automatically scroll to the bottom of the conversation. Users have to manually scroll down to see new messages, which can be inconvenient.

**Expected behavior:** The chat window should automatically scroll to the bottom of the conversation whenever a new message is sent or received.

**Steps to reproduce:**

- Open the app
- Navigate to the chat feature
- Scroll up to view older messages
- Wait for a new message to be sent or received
- Notice that the chat window does not automatically scroll to the bottom

**Proposed solution:** To fix this issue, we should use the scrollIntoView method in combination with useRef. When a new message is received or sent, we can call the scrollIntoView method on the last message in the chat window to scroll the window to the bottom.

**Comment by itzVort3x1** [comment]
I have started working on this issue. How do i start a conversation with a person? I have opened in two different browsers with two different users. The edit button or the search does not seem to work. Please guide me regarding this issue. Thank you.

**Comment by ruveydayilmaz** [comment]
Hi @itzVort3x1, thanks for your help! I haven't implemented the new conversation feature yet. You can manually add it to your database.

**Comment by nguyen-tuan-hiep** [comment]
I can't see other user on the left navigation
![image](https://github.com/ruveydayilmaz/realtime-chat-app/assets/75298858/e058fd26-a4d0-4462-ae3a-a0034f8efe56)

**Comment by ruveydayilmaz** [comment]
Hi @nguyen-tuan-hiep , have you added another user and created a new conversation from your database?

**Comment by itzVort3x1** [comment]
@ruveydayilmaz It would be great if you could give a sample of what needs to be inserted and into which model. I am assuming I have to updated the chat collection. It has one property of members. So if this is correct please give me a better understanding of what the array contains.

**Comment by ruveydayilmaz** [comment]
@itzVort3x1 
A chat model contains 2 user IDs.
![image](https://github.com/ruveydayilmaz/realtime-chat-app/assets/74985368/dbb83c93-06c3-4763-9057-ebb8e1cd5773)

**Comment by itzVort3x1** [comment]
> @itzVort3x1 A chat model contains 2 user IDs. ![image](https://user-images.githubusercontent.com/74985368/241550082-dbb83c93-06c3-4763-9057-ebb8e1cd5773.png)

Great it's working now! thank you for the assistance.

**Comment by itzVort3x1** [comment]
@ruveydayilmaz Perfect! it's working now, thank you for your assistance.

**Comment by itzVort3x1** [comment]
@ruveydayilmaz I have created a Pull request with the fix. Hope it helps. If there is any thing else I could contribute with would love to collaborate!

**Comment by nguyen-tuan-hiep** [comment]
> Hi @nguyen-tuan-hiep , have you added another user and created a new conversation from your database?

yes, I’ve got an error when just creating 2 users. For multiple users (>2), it worked fine

**Comment by ruveydayilmaz** [comment]
> @ruveydayilmaz I have created a Pull request with the fix. Hope it helps. If there is any thing else I could contribute with would love to collaborate!

Thanks again! I plan to slowly add new features and eventually refactor the code. I'll let you know when I need help 🙌🏻

**Comment by nguyen-tuan-hiep** [comment]
Do I have to manually add 2 members to the chat model  in mongodb compass ? @ruveydayilmaz
